### PR TITLE
Add Passport integration. Fixes the refresh bug.

### PR DESCRIPTION
**Pull request by hzach**
I've also included some changes to the back-end which will secure REST endpoints. Review them and see what you think. I've also added a lot of docs in the routes. More to come. In the future I will not make such massive PRs.

### CODE REVIEW

**Comment by hzach** [comment]
So, I must have accidentally deleted a bracket when I was merging `projectCtrl.js`. Lesson learned; I will be more careful and lint after I manually merge files in the future. Now that that is resolved, I'm running `gulp test` (after changing `config.js` to point to my local test environment, which isn't being tracked right now btw) I get the following output:
screenshot from 2015-07-19 20 50 50

**Comment by tyleranton** [comment]
Did you add Google and GitHub? I don't see it anywhere within the web app itself.

**Comment by tyleranton** [comment]
So I checked out your branch, ran the tests against a fresh (local) database, and it still failed hard. Make sure that whatever tests you have locally are the same that you committed. It doesn't look like a database issue anymore. It's code level.

**Comment by tyleranton** [comment]
Actually, running tests from your branch crashes the production site lol.

**Comment by hzach** [comment]
I haven't committed the Google or Github OAuth yet. I wanted to integrate the local strategy into production first so that I can start making smaller pulls. I'm definitely running the same tests locally.

**Comment by hzach** [comment]
Wait are you not testing with a local deployment? Can you post some output?

**Comment by tyleranton** [comment]
Okay yea, never mind. It works locally.

**Comment by tyleranton** [comment]
But, whatever the problem is with production, it crashes the hell out of it.

**Comment by hzach** [comment]
Does the output look the same as the Travis build output?

**Comment by tyleranton** [comment]
Yea I believe so

**Comment by tyleranton** [comment]
STILL BROKEN

**Comment by tyleranton** [comment]
Okay so, team page is broken. User info isn't displaying on the panels. Also, team members aren't showing up in the list of users to `assign` someone to a task.

**Comment by hzach** [comment]
I can't see where to assign members to tasks in production right now. Is that functionality that is currently in place? Also, you can fix the team page like this:
in `team.html` in lines `44` and `45`, change
```html
 <h4>{{ user.firstName }} {{ user.lastName }}</h4>
  <p>{{ user.username }}</p>
```
to
```html
 <h4>{{ user.local.firstName }} {{ user.local.lastName }}</h4>
 <p>{{ user.local.username }}</p>
```
I can't make these changes right now but will ASAP

**Comment by tyleranton** [comment]
We need to find a way to avoid having to include the strategy or else we're going to have to do a bunch of `ng-if` directives in the html.

**Comment by tyleranton** [comment]
And yea you can assign users to tasks in production

**Comment by hzach** [comment]
For some reason, I don't have the option of assigning users to task from my account, even on projects that I own. I agree about hiding the strategy details. I think this should be straightforward though. Instead we can just have child objects in the `User` schema that contain the auth details of each strategy and put relevant user data directly in the schema. Then it will be up to the `userRouter` to deal with each strategy on sign-up.

**Comment by tyleranton** [comment]
If you go to production, you can see that you can assign users to tasks.

**Comment by tyleranton** [comment]
`fix for task page and team page`

WHAT FIX IT'S STILL NOT WORKING

**Comment by tyleranton** [comment]
Comments need to show the user who is commentiNG BUT OF COURSE YOU WOULDN'T KNOW THAT BECAUSE YOU DIDN'T TEST IT BECAUSE YOU DON'T EVEN KNOW WHAT CROCKPOT IS FIGHT ME M8

**Comment by tyleranton** [comment]
But other than that, it looks just about ready to merge.

**Comment by tyleranton** [comment]
```
describe("POST /user/users", function() {
    it('should save user successfully and return user data', function(done) {
      request(url)
        .post('/user/users')
        .send(user)
        .end(function(err, res) {
          if (err) throw err;


          // check properties of object
          res.body.should.have.property('user');
          res.body.user.should.have.property('_id');
          res.body.should.have.property('message');
          res.body.should.have.property('success');

          res.body.success.should.equal(true);

          // user check attributes
          res.body.user.local.firstName.should.equal(user.firstName);
          res.body.user.local.lastName.should.equal(user.lastName);
          res.body.user.local.email.should.equal(user.email);
          res.body.user.local.username.should.equal(user.username);
          res.body.user.local.password.should.not.equal(user.password);

          user._id = res.body.user._id;

          done();
        });
    });
  });
```


`res.body.user.local.email.should.equal(user.email);` <-- that test is failing hard

**Pull request merged**
